### ISSUE TITLE
farseer is not a constructor

### ISSUE THREAD

**Issue by fcasco** [gregstewart/farseer#35]
this code:

```
var Farseer = require('farseer');
var farseer = new Farseer();
```

gives this error:
```
farseer = new Farseer();
          ^

TypeError: Farseer is not a constructor
    at Object.<anonymous> (/home/facundo/code/deckstats/index.js:5:11)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```
with node --version
v8.1.2

**Comment by gregstewart** [comment]
Hi @fcasco,

Did you try (as per the very lightweight documentation in the README) to require it as follows:

```javascript
var Farseer = require('farseer').default;
var farseer = new Farseer();

farseer.on('zone-change', function (data) {
  console.log(data.cardName + ' has moved from ' + data.fromTeam + ' ' + data.fromZone + ' to ' + data.toTeam + ' ' + data.toZone);
});

farseer.start();
```

Note the `.default` when requiring the module.

**Comment by gregstewart** [comment]
Closing due to innactivity
